### ISSUE TITLE
Exception error when environment USER is not set

### ISSUE THREAD

**Issue by woopstar** [dotmanila/pyxbackup#13]
The program crashes with exception:

```
Traceback (most recent call last):
  File "/root/pyxbackup", line 2551, in <module>
    xb_user = os.environ["USER"]
  File "/usr/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'USER'
[04/08/2015 19:17:01] FATAL: An exception error has occurred!
Traceback (most recent call last):
  File "/root/pyxbackup", line 2622, in <module>
    _die("An exception error has occurred!")
  File "/root/pyxbackup", line 164, in _die
    raise Exception(str(msgs))
Exception: ('An exception error has occurred!',)
```

when:

```
xb_user = os.environ["USER"]
```

USER is not set in the environment. Consider do a sanity check here? 
Problem was observed when running from cron.

**Comment by dotmanila** [comment]
Switched to a more portable pwd.getpwuid(os.getuid())[0] instead :)
